## Manejo Basico de datos con PANDAS.

In [10]:
# Importando librerias.
import pandas as pd
import os
import numpy as np

In [8]:
# Importando datasets from datafiles.
mainpath = "/proyectos/learning/MachineLearning/datasets/aprendizaje-autom-profundo/house_data/"
outputs = "/proyectos/learning/MachineLearning/datasets/aprendizaje-autom-profundo/outputs/"
filename = "data.csv"
urldata = "https://www.kaggle.com/datasets/shree1992/housedata"
fullpath = os.path.join(mainpath, filename)
df = pd.read_csv(fullpath)

In [4]:
print(df)

                     date         price  bedrooms  bathrooms  sqft_living  \
0     2014-05-02 00:00:00  3.130000e+05       3.0       1.50         1340   
1     2014-05-02 00:00:00  2.384000e+06       5.0       2.50         3650   
2     2014-05-02 00:00:00  3.420000e+05       3.0       2.00         1930   
3     2014-05-02 00:00:00  4.200000e+05       3.0       2.25         2000   
4     2014-05-02 00:00:00  5.500000e+05       4.0       2.50         1940   
...                   ...           ...       ...        ...          ...   
4595  2014-07-09 00:00:00  3.081667e+05       3.0       1.75         1510   
4596  2014-07-09 00:00:00  5.343333e+05       3.0       2.50         1460   
4597  2014-07-09 00:00:00  4.169042e+05       3.0       2.50         3010   
4598  2014-07-10 00:00:00  2.034000e+05       4.0       2.00         2090   
4599  2014-07-10 00:00:00  2.206000e+05       3.0       2.50         1490   

      sqft_lot  floors  waterfront  view  condition  sqft_above  \
0       

In [5]:
# Imprimiendo las 5 primeras filas del dataframe.
df.head()

date      price  bedrooms  bathrooms  sqft_living  sqft_lot  \
0  2014-05-02 00:00:00   313000.0       3.0       1.50         1340      7912   
1  2014-05-02 00:00:00  2384000.0       5.0       2.50         3650      9050   
2  2014-05-02 00:00:00   342000.0       3.0       2.00         1930     11947   
3  2014-05-02 00:00:00   420000.0       3.0       2.25         2000      8030   
4  2014-05-02 00:00:00   550000.0       4.0       2.50         1940     10500   

   floors  waterfront  view  condition  sqft_above  sqft_basement  yr_built  \
0     1.5           0     0          3        1340              0      1955   
1     2.0           0     4          5        3370            280      1921   
2     1.0           0     0          4        1930              0      1966   
3     1.0           0     0          4        1000           1000      1963   
4     1.0           0     0          4        1140            800      1976   

   yr_renovated                    street       city  statezip country  
0          2005      18810 Densmore Ave N  Shoreline  WA 98133     USA  
1             0           709 W Blaine St    Seattle  WA 98119     USA  
2             0  26206-26214 143rd Ave SE       Kent  WA 98042     USA  
3             0           857 170th Pl NE   Bellevue  WA 98008     USA  
4          1992         9105 170th Ave NE    Redmond  WA 98052     USA

In [6]:
# Obteniendo indice de las columns del dataframe.
df.columns

Index(['date', 'price', 'bedrooms', 'bathrooms', 'sqft_living', 'sqft_lot',
       'floors', 'waterfront', 'view', 'condition', 'sqft_above',
       'sqft_basement', 'yr_built', 'yr_renovated', 'street', 'city',
       'statezip', 'country'],
      dtype='object')

In [7]:
# Obteniendo cantidad de filas y columnas.
df.shape

(4600, 18)

In [8]:
# Obteniendo la fila en la posicion 10.
df.iloc[9]

date             2014-05-02 00:00:00
price                       640000.0
bedrooms                         4.0
bathrooms                        2.0
sqft_living                     1520
sqft_lot                        6200
floors                           1.5
waterfront                         0
view                               0
condition                          3
sqft_above                      1520
sqft_basement                      0
yr_built                        1945
yr_renovated                    2010
street              6811 55th Ave NE
city                         Seattle
statezip                    WA 98115
country                          USA
Name: 9, dtype: object

In [9]:
# Obteniendo las primeras 10 filas.
df.iloc[:10]

date      price  bedrooms  bathrooms  sqft_living  sqft_lot  \
0  2014-05-02 00:00:00   313000.0       3.0       1.50         1340      7912   
1  2014-05-02 00:00:00  2384000.0       5.0       2.50         3650      9050   
2  2014-05-02 00:00:00   342000.0       3.0       2.00         1930     11947   
3  2014-05-02 00:00:00   420000.0       3.0       2.25         2000      8030   
4  2014-05-02 00:00:00   550000.0       4.0       2.50         1940     10500   
5  2014-05-02 00:00:00   490000.0       2.0       1.00          880      6380   
6  2014-05-02 00:00:00   335000.0       2.0       2.00         1350      2560   
7  2014-05-02 00:00:00   482000.0       4.0       2.50         2710     35868   
8  2014-05-02 00:00:00   452500.0       3.0       2.50         2430     88426   
9  2014-05-02 00:00:00   640000.0       4.0       2.00         1520      6200   

   floors  waterfront  view  condition  sqft_above  sqft_basement  yr_built  \
0     1.5           0     0          3        1340              0      1955   
1     2.0           0     4          5        3370            280      1921   
2     1.0           0     0          4        1930              0      1966   
3     1.0           0     0          4        1000           1000      1963   
4     1.0           0     0          4        1140            800      1976   
5     1.0           0     0          3         880              0      1938   
6     1.0           0     0          3        1350              0      1976   
7     2.0           0     0          3        2710              0      1989   
8     1.0           0     0          4        1570            860      1985   
9     1.5           0     0          3        1520              0      1945   

   yr_renovated                    street          city  statezip country  
0          2005      18810 Densmore Ave N     Shoreline  WA 98133     USA  
1             0           709 W Blaine St       Seattle  WA 98119     USA  
2             0  26206-26214 143rd Ave SE          Kent  WA 98042     USA  
3             0           857 170th Pl NE      Bellevue  WA 98008     USA  
4          1992         9105 170th Ave NE       Redmond  WA 98052     USA  
5          1994            522 NE 88th St       Seattle  WA 98115     USA  
6             0         2616 174th Ave NE       Redmond  WA 98052     USA  
7             0         23762 SE 253rd Pl  Maple Valley  WA 98038     USA  
8             0   46611-46625 SE 129th St    North Bend  WA 98045     USA  
9          2010          6811 55th Ave NE       Seattle  WA 98115     USA

In [10]:
# Obteniendo la celda (0,1) interceptando fila 0 y columna 1
df.iloc[0,1]

313000.0

In [11]:
# Obteniendo las 5 primeras columnas de las filas 0,1 y 2
df.iloc[[0,1,2], :5]

date      price  bedrooms  bathrooms  sqft_living
0  2014-05-02 00:00:00   313000.0       3.0        1.5         1340
1  2014-05-02 00:00:00  2384000.0       5.0        2.5         3650
2  2014-05-02 00:00:00   342000.0       3.0        2.0         1930

In [12]:
# Obtener el valor de la columna precio de la primera fila.
df.loc[0, 'price']

313000.0

In [14]:
# Obtener las primeras filas ddesde la 0 hasta la 3 con las columnas desde price a bathrooms.
df.loc[:3, 'price': 'bathrooms']

price  bedrooms  bathrooms
0   313000.0       3.0       1.50
1  2384000.0       5.0       2.50
2   342000.0       3.0       2.00
3   420000.0       3.0       2.25

In [15]:
# Generar una descripcion ddetallada de los datos.
df.describe()

price     bedrooms    bathrooms   sqft_living      sqft_lot  \
count  4.600000e+03  4600.000000  4600.000000   4600.000000  4.600000e+03   
mean   5.519630e+05     3.400870     2.160815   2139.346957  1.485252e+04   
std    5.638347e+05     0.908848     0.783781    963.206916  3.588444e+04   
min    0.000000e+00     0.000000     0.000000    370.000000  6.380000e+02   
25%    3.228750e+05     3.000000     1.750000   1460.000000  5.000750e+03   
50%    4.609435e+05     3.000000     2.250000   1980.000000  7.683000e+03   
75%    6.549625e+05     4.000000     2.500000   2620.000000  1.100125e+04   
max    2.659000e+07     9.000000     8.000000  13540.000000  1.074218e+06   

            floors   waterfront         view    condition   sqft_above  \
count  4600.000000  4600.000000  4600.000000  4600.000000  4600.000000   
mean      1.512065     0.007174     0.240652     3.451739  1827.265435   
std       0.538288     0.084404     0.778405     0.677230   862.168977   
min       1.000000     0.000000     0.000000     1.000000   370.000000   
25%       1.000000     0.000000     0.000000     3.000000  1190.000000   
50%       1.500000     0.000000     0.000000     3.000000  1590.000000   
75%       2.000000     0.000000     0.000000     4.000000  2300.000000   
max       3.500000     1.000000     4.000000     5.000000  9410.000000   

       sqft_basement     yr_built  yr_renovated  
count    4600.000000  4600.000000   4600.000000  
mean      312.081522  1970.786304    808.608261  
std       464.137228    29.731848    979.414536  
min         0.000000  1900.000000      0.000000  
25%         0.000000  1951.000000      0.000000  
50%         0.000000  1976.000000      0.000000  
75%       610.000000  1997.000000   1999.000000  
max      4820.000000  2014.000000   2014.000000

In [15]:
# Generar una descripcion ddetallada de todos los datos incluyendos los NO numericos.
df.describe(include='all')

date         price     bedrooms    bathrooms  \
count                  4600  4.600000e+03  4600.000000  4600.000000   
unique                   70           NaN          NaN          NaN   
top     2014-06-23 00:00:00           NaN          NaN          NaN   
freq                    142           NaN          NaN          NaN   
mean                    NaN  5.519630e+05     3.400870     2.160815   
std                     NaN  5.638347e+05     0.908848     0.783781   
min                     NaN  0.000000e+00     0.000000     0.000000   
25%                     NaN  3.228750e+05     3.000000     1.750000   
50%                     NaN  4.609435e+05     3.000000     2.250000   
75%                     NaN  6.549625e+05     4.000000     2.500000   
max                     NaN  2.659000e+07     9.000000     8.000000   

         sqft_living      sqft_lot       floors   waterfront         view  \
count    4600.000000  4.600000e+03  4600.000000  4600.000000  4600.000000   
unique           NaN           NaN          NaN          NaN          NaN   
top              NaN           NaN          NaN          NaN          NaN   
freq             NaN           NaN          NaN          NaN          NaN   
mean     2139.346957  1.485252e+04     1.512065     0.007174     0.240652   
std       963.206916  3.588444e+04     0.538288     0.084404     0.778405   
min       370.000000  6.380000e+02     1.000000     0.000000     0.000000   
25%      1460.000000  5.000750e+03     1.000000     0.000000     0.000000   
50%      1980.000000  7.683000e+03     1.500000     0.000000     0.000000   
75%      2620.000000  1.100125e+04     2.000000     0.000000     0.000000   
max     13540.000000  1.074218e+06     3.500000     1.000000     4.000000   

          condition   sqft_above  sqft_basement     yr_built  yr_renovated  \
count   4600.000000  4600.000000    4600.000000  4600.000000   4600.000000   
unique          NaN          NaN            NaN          NaN           NaN   
top             NaN          NaN            NaN          NaN           NaN   
freq            NaN          NaN            NaN          NaN           NaN   
mean       3.451739  1827.265435     312.081522  1970.786304    808.608261   
std        0.677230   862.168977     464.137228    29.731848    979.414536   
min        1.000000   370.000000       0.000000  1900.000000      0.000000   
25%        3.000000  1190.000000       0.000000  1951.000000      0.000000   
50%        3.000000  1590.000000       0.000000  1976.000000      0.000000   
75%        4.000000  2300.000000     610.000000  1997.000000   1999.000000   
max        5.000000  9410.000000    4820.000000  2014.000000   2014.000000   

                       street     city  statezip country  
count                    4600     4600      4600    4600  
unique                   4525       44        77       1  
top     2520 Mulberry Walk NE  Seattle  WA 98103     USA  
freq                        4     1573       148    4600  
mean                      NaN      NaN       NaN     NaN  
std                       NaN      NaN       NaN     NaN  
min                       NaN      NaN       NaN     NaN  
25%                       NaN      NaN       NaN     NaN  
50%                       NaN      NaN       NaN     NaN  
75%                       NaN      NaN       NaN     NaN  
max                       NaN      NaN       NaN     NaN

In [5]:
# Eliminando columnas del dataframe.
df.drop(columns=['view'])

date         price  bedrooms  bathrooms  sqft_living  \
0     2014-05-02 00:00:00  3.130000e+05       3.0       1.50         1340   
1     2014-05-02 00:00:00  2.384000e+06       5.0       2.50         3650   
2     2014-05-02 00:00:00  3.420000e+05       3.0       2.00         1930   
3     2014-05-02 00:00:00  4.200000e+05       3.0       2.25         2000   
4     2014-05-02 00:00:00  5.500000e+05       4.0       2.50         1940   
...                   ...           ...       ...        ...          ...   
4595  2014-07-09 00:00:00  3.081667e+05       3.0       1.75         1510   
4596  2014-07-09 00:00:00  5.343333e+05       3.0       2.50         1460   
4597  2014-07-09 00:00:00  4.169042e+05       3.0       2.50         3010   
4598  2014-07-10 00:00:00  2.034000e+05       4.0       2.00         2090   
4599  2014-07-10 00:00:00  2.206000e+05       3.0       2.50         1490   

      sqft_lot  floors  waterfront  condition  sqft_above  sqft_basement  \
0         7912     1.5           0          3        1340              0   
1         9050     2.0           0          5        3370            280   
2        11947     1.0           0          4        1930              0   
3         8030     1.0           0          4        1000           1000   
4        10500     1.0           0          4        1140            800   
...        ...     ...         ...        ...         ...            ...   
4595      6360     1.0           0          4        1510              0   
4596      7573     2.0           0          3        1460              0   
4597      7014     2.0           0          3        3010              0   
4598      6630     1.0           0          3        1070           1020   
4599      8102     2.0           0          4        1490              0   

      yr_built  yr_renovated                    street       city  statezip  \
0         1955          2005      18810 Densmore Ave N  Shoreline  WA 98133   
1         1921             0           709 W Blaine St    Seattle  WA 98119   
2         1966             0  26206-26214 143rd Ave SE       Kent  WA 98042   
3         1963             0           857 170th Pl NE   Bellevue  WA 98008   
4         1976          1992         9105 170th Ave NE    Redmond  WA 98052   
...        ...           ...                       ...        ...       ...   
4595      1954          1979            501 N 143rd St    Seattle  WA 98133   
4596      1983          2009          14855 SE 10th Pl   Bellevue  WA 98007   
4597      2009             0          759 Ilwaco Pl NE     Renton  WA 98059   
4598      1974             0         5148 S Creston St    Seattle  WA 98178   
4599      1990             0         18717 SE 258th St  Covington  WA 98042   

     country  
0        USA  
1        USA  
2        USA  
3        USA  
4        USA  
...      ...  
4595     USA  
4596     USA  
4597     USA  
4598     USA  
4599     USA  

[4600 rows x 17 columns]

In [9]:
# Exportando dataset a csv en disco local.
df.to_csv(outputs+'precios_casas2.csv',index=False)

## Manejo de Arreglos con Numpy.

In [11]:
# Creacion de un vector con cinco (5) elementos.
vec1 = np.array([1,2,3,4,5])

In [12]:
# visualizando los elementos del vector.
print(vec1)

[1 2 3 4 5]


In [16]:
# Visualizando las dimenciones del vector.
vec1.shape

(5,)

In [17]:
# Creacion de Matriz 3 X 3.
matriz = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

In [18]:
# Visualizando los elementos de la matriz.
matriz

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [19]:
# Visualizando las dimenciones de la Matriz.
matriz.shape

(3, 3)

In [20]:
# Creando un vector de ceros, con la funcion zeros().
vec2 = np.zeros(4)

In [21]:
# Imprimiendo el vector.
vec2

array([0., 0., 0., 0.])

In [23]:
# Creando una matriz de 2 X 3  de ceros, con la funcion zeros().
matriz2 = np.zeros((2,3))

In [24]:
# Imprimiendo la matriz de ceros
matriz2

array([[0., 0., 0.],
       [0., 0., 0.]])

In [25]:
# Matriz de numeros aleatorios con la funcion Random.
matriz3 = np.random.random((2,4))

In [26]:
# Imprimiendo matriz de numeros aleatorios.
matriz3

array([[0.36621908, 0.4653273 , 0.78314036, 0.71322484],
       [0.07494507, 0.55146351, 0.25093389, 0.63349269]])